export const MOODS = [
  // Common Moods
  { name: "Happy", rarity: "common" },
  { name: "Chill", rarity: "common" },
  { name: "Excited", rarity: "common" },
  { name: "Sad", rarity: "common" },
  { name: "Angry", rarity: "common" },
  { name: "Tired", rarity: "common" },
  { name: "Calm", rarity: "common" },
  { name: "Energetic", rarity: "common" },
  { name: "Peaceful", rarity: "common" },
  { name: "Anxious", rarity: "common" },
  { name: "Confident", rarity: "common" },
  { name: "Lonely", rarity: "common" },
  { name: "Loved", rarity: "common" },
  { name: "Motivated", rarity: "common" },
  { name: "Bored", rarity: "common" },

  // Rare Moods
  { name: "Nostalgic", rarity: "rare" },
  { name: "Contemplative", rarity: "rare" },
  { name: "Whimsical", rarity: "rare" },
  { name: "Melancholic", rarity: "rare" },
  { name: "Inspired", rarity: "rare" },
  { name: "Peaceful", rarity: "rare" },
  { name: "Hopeful", rarity: "rare" },
  { name: "Playful", rarity: "rare" },
  { name: "Grateful", rarity: "rare" },
  { name: "Adventurous", rarity: "rare" },
  { name: "Sentimental", rarity: "rare" },
  { name: "Curious", rarity: "rare" },
  { name: "Serene", rarity: "rare" },
  { name: "Daring", rarity: "rare" },
  { name: "Thoughtful", rarity: "rare" },

  // Shiny Moods (Ultra Rare)
  { name: "Transcendent", rarity: "shiny" },
  { name: "Ethereal", rarity: "shiny" },
  { name: "Euphoric", rarity: "shiny" },
  { name: "Luminous", rarity: "shiny" },
  { name: "Celestial", rarity: "shiny" },
  { name: "Blissful", rarity: "shiny" },
  { name: "Enchanted", rarity: "shiny" },
  { name: "Magical", rarity: "shiny" },
  { name: "Cosmic", rarity: "shiny" },
  { name: "Infinite", rarity: "shiny" },
  { name: "Awakened", rarity: "shiny" },
  { name: "Ethereal Bliss", rarity: "shiny" },
];